[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[client]
caching = false
showErrorDetails = true
toolbarMode = "minimal"

[global]
developmentMode = false
suppressDeprecationWarnings = true

[theme]
base = "light"
